# This is a workflow example relying on docker-coq-action.
name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.14.1'
          - '8.15.2'
          - dev
        ocaml_version:
          - '4.13.1-flambda'
      max-parallel: 4
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        # See https://github.com/coq-community/docker-coq-action#readme
        # for details on docker-coq-action's syntax and provided features.
        with:
          # Add extra repository for coq-json ( https://github.com/liyishuai/coq-json )
          # the || true is required for the dev builds that may have extra repo, see https://github.com/coq-community/docker-coq-action/issues/64
          before_install: |
            opam repo add  --all-switches --set-default coq-released https://coq.inria.fr/opam/released || true
            opam repo add  --all-switches --set-default coq-extra-dev https://coq.inria.fr/opam/extra-dev/ || true
            opam pin add -n -y coq-kruskal-trees https://github.com/DmxLarchey/Kruskal-Trees.git || true
            opam repo list

          opam_file: 'coq-oqarina.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: 'OPAMWITHTEST'
        env:
          OPAMWITHTEST: 'true'
